# Use postgres/example user/password credentials
version: '3.1'

services:

  dbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: dblibros
    volumes:
    - ./posgresdb:/var/lib/postgresql/data

  app:
    image: ddsdeploy
    restart: always
    ports:
      - 8080:8080
    environment:
       hibernate__hbm2ddl__auto: create
       javax__persistence__jdbc__driver: org.postgresql.Driver
       javax__persistence__jdbc__password: g02OqC4A1sRnd2TpF6ONLRT3Qg63EHrd
       DATABASE_URL: jdbc:postgresql://dpg-crvat2hu0jms73ao34r0-a.oregon-postgres.render.com:5432/dbservice
       javax__persistence__jdbc__user: postgresql
    depends_on:
     - dbservice
