version: '3.1'

services:

  dbservice:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}  
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ddsdeploy
    restart: always
    ports:
      - 8080:8080
    environment:
      hibernate__hbm2ddl__auto: update
      javax__persistence__jdbc__driver: org.postgresql.Driver
      javax__persistence__jdbc__url: jdbc:postgresql://dbservice:5432/${POSTGRES_DB}
      javax__persistence__jdbc__user: postgres
      javax__persistence__jdbc__password: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@dbservice:5432/${POSTGRES_DB}
    depends_on:
      dbservice:
        condition: service_healthy
